[project]
name = "dict-from-annotation"
version = "0.0.2"
description = "Command-line interface (CLI) to create a pronunciation dictionary based on annotations."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {email = "pypi@stefantaubert.com"},
  {name = "Stefan Taubert"}
]
maintainers = [
  {email = "pypi@stefantaubert.com"},
  {name = "Stefan Taubert"}
]
keywords = [
  "ARPAbet",
  "IPA",
  "X-SAMPA",
  "CMU",
  "TTS",
  "Text-to-speech",
  "Speech synthesis",
  "praat",
  "Language",
  "Linguistics"  
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Operating System :: OS Independent",
  "Operating System :: MacOS",
  "Operating System :: POSIX",
  "Operating System :: POSIX :: BSD",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Unix",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: MIT License",
]
dependencies = [
  "iterable-serialization>=0.0.1",
  "pronunciation-dictionary>=0.0.4",
  "ordered-set>=4.1.0",
  "tqdm",
]

[project.urls]
Homepage = "https://github.com/stefantaubert/dict-from-annotation"
Issues = "https://github.com/stefantaubert/dict-from-annotation/issues"

[project.scripts]
dict-from-annotation-cli = "dict_from_annotation.cli:run"

[tool.setuptools.packages.find]
where = ["src"]
include = [
  "dict_from_annotation",
]
exclude = [
  "dict_from_annotation_tests",
  "dict_from_annotation_debug"
]
namespaces = true

[tool.pytest.ini_options]
log_cli = true
log_level = "DEBUG"
testpaths = [
  "src/dict_from_annotation_tests",
]

[tool.autopep8]
indent-size = 2
ignore = ["E121"]
max_line_length = 100

[tool.isort]
line_length = 100
indent = 2
known_first_party = [
  "dict_from_annotation",
]
known_third_party = [
  "iterable_serialization",
  "pronunciation_dictionary",
  "ordered_set"
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{38,39,310}
isolated_build = True

[testenv]
deps = 
  pytest
commands = 
  pytest
  dict-from-annotation-cli
  dict-from-annotation-cli -v
"""

[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
